### ISSUE TITLE
Usage of parseURL without input escaping

### ISSUE THREAD

**Issue by michaxm** [afcowie/http-streams#110]
Can't parse URI http://sdf.sdf/α
CallStack (from HasCallStack):
  error, called at lib/Network/Http/Inconvenience.hs:267 [264-268 now]

parseURI might just be needing: `escapeURIString isUnescapedInURI` for its input, as mentioned here:
https://stackoverflow.com/questions/36681058/why-does-network-uri-parseuri-not-like-the-pipe-character

I will probably propose a pull request regarding this inline 268, after tying up another loose thread.

Side note: IMO failing with an error is unexpected behaviour for a library.

**Comment by afcowie** [comment]
Hey.

> Side note: IMO failing with an error is unexpected behaviour for a library.

I agree. We've learned a bit as a community since I first wrote this code. There are places where it fails to parse malformed HTTP headers and just barfs unhelpfully. Yeay **attoparsec**. Oh well.

It's not immediately obvious to me where to wrap this because right now the external API doesn't report failure in its type. We might consider changing that.

I _am_ ok with IO actions throwing exceptions, in the case of e.g. network failure. It's IO; a caller has to deal with that explicitly. But we can be clean and deliberate about it. We shouldn't be borking out of pure code, hell no.

AfC
