### ISSUE TITLE
Cannot send requests concurrently

### ISSUE THREAD

**Issue by dmjio** [afcowie/http-streams#74]
After establishing a connection to another http-server, when two send/receive actions are run concurrently, the results can be unpredictable (i.e. parse failures). Was wondering what the recommended way to send requests concurrently is (if possible). These tests were run under `ghci` and an executable compiled with `ghc -rtsopts -threaded`

Example
```haskell
------------------------------------------------------------------------------
-- | Request Builder for API
buildHNRequest :: FromJSON a => Text -> HackerNews (Maybe a)
buildHNRequest url = do
    con <- ask
    liftIO $ do
      req <- buildRequest $ do
        http GET $ "/v0`/" <> T.encodeUtf8 url <> ".json"
        setHeader "Connection" "Keep-Alive"
        setAccept "application/json"
      let action = do sendRequest con req emptyBody
                      receiveResponse con $ const Streams.read
      c <- concurrently action action
      return $ case fst c of
        Nothing -> Nothing
        Just bs -> do
          let xs = rights [parseOnly value bs, parseOnly json bs]
          case xs of
            []    -> Nothing
            x : _ ->
              case fromJSON x of
                Success a -> Just a
                _         -> Nothing
```

Result, first works fine, second fails (goes back and forth like this).

```haskell
λ> main
Just (User {userAbout = Nothing, userCreated = 2013-08-06 16:49:23 UTC, userDelay = 0, userId = UserId "dmjio", userKarma = 7, userSubmitted = [8433827,8429256,8429161,8429069,8374809,8341570,7919268,78\
25469,7350544,7327291,6495994,6352317,6168527,6168524,6167639], userDeleted = False, userDead = False})
λ> main
*** Exception: Parse exception: Failed reading: takeWith
λ>
```

**Comment by afcowie** [comment]
If you're going to HTTP pipeline over a single connection _you_ must read responses in the order the requests were sent. See discussion at [`openConnection`](https://hackage.haskell.org/package/http-streams/docs/Network-Http-Client.html#v:openConnection) or the RFC for HTTP [pipelining](http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html) if you're interested in further detail.

I'm a little better at Haskell than I was when I first wrote this, so I daresay when I get around to refactoring my HTTP client library I will make Request to Response over Connection a single action so that invariants are enforced. But in the mean time, **http-streams** is a low level -ish library, and so I'm afraid it's up to you.

For concurrency the way you're trying to do it, open separate connections to the server for each thread.

AfC
