### ISSUE TITLE
Test suite run failure

### ISSUE THREAD

**Issue by snoyberg** [afcowie/http-streams#90]
Now that the test suite can be built by Stackage, I ran into the following:

```
Test suite snippet: RUNNING...
1
snippet: connect: does not exist (Connection refused)
Test suite snippet: FAIL
Test suite logged to: /home/stackage/work/logs/nightly/http-streams-0.8.3.2/test-run.out
```

Is this anticipated?

**Comment by afcowie** [comment]
Grr. I thought I'd fixed that! `snippet` was just that, a cabal definition for hacking, not a test suite. I didn't remove it because it was the example program I used when hacking; meant to put `buildable: false` in instead. Sorry. Maybe I'll just get rid of the block from the cabal file.

[I wish there was a category of {library, executable, test-suite, etc} that was for casual programs. Seems like it's pretty common to have such things, but their neither test suites nor "the executable that this package represents"; not like you need my test snippet in your _~/.local/bin/_]

@snoyberg I'll nuke the block. 0.8.3.3 coming right up.

AfC
